name: Build Code By Thánh Nữ v0.5.6 API Portable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm install

      - name: Build portable EXE
        run: npm run dist

      - uses: actions/upload-artifact@v4
        with:
          name: ThanhNu-v05-API-Windows-Portable
          path: dist/*.exe
